### ISSUE TITLE
Error: mdatLength less than chunkLength in sometime

### ISSUE THREAD

**Issue by MinChanSike** [kevinGodell/mse-live-player#1]
Hi, your sharing is very valuable.
I got some issue when I try to test 3 external **rtsp** stream for a couple minutes, nodeJs service was stopped in sometime.
The error message and log are below.
Thank you in advance for any help.

```
E:\Sources\Testing\mseLivePlayer\node_modules\mp4frag\index.js:438
                throw new Error('mdatLength less than chunkLength');
                ^

Error: mdatLength less than chunkLength
    at Mp4Frag._findMdat (E:\Sources\Testing\mseLivePlayer\node_modules\mp4frag\index.js:438:23)
    at Mp4Frag._findMoof (E:\Sources\Testing\mseLivePlayer\node_modules\mp4frag\index.js:333:18)
    at Mp4Frag._transform (E:\Sources\Testing\mseLivePlayer\node_modules\mp4frag\index.js:448:14)
    at Mp4Frag.Transform._read (_stream_transform.js:186:10)
    at Mp4Frag.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Mp4Frag.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mse-live-player@0.0.1 start: `node compare.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mse-live-player@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ThuKha\AppData\Roaming\npm-cache\_logs\2018-01-16T05_53_22_622Z-debug.log
```
```
2018-01-16T05_53_22_622Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mse-live-player@0.0.1~prestart: mse-live-player@0.0.1
6 info lifecycle mse-live-player@0.0.1~start: mse-live-player@0.0.1
7 verbose lifecycle mse-live-player@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle mse-live-player@0.0.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\Sources\Testing\mseLivePlayer\node_modules\.bin;C:\Program Files\Microsoft MPI\Bin\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Users\ThuKha\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\ThuKha\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\ThuKha\AppData\Local\Programs\Python\Python36\;C:\Program Files\Microsoft VS Code\bin;C:\Users\ThuKha\AppData\Roaming\npm;C:\Program Files\Docker Toolbox;E:\3)Installers\ffmpeg\bin;
9 verbose lifecycle mse-live-player@0.0.1~start: CWD: E:\Sources\Testing\mseLivePlayer
10 silly lifecycle mse-live-player@0.0.1~start: Args: [ '/d /s /c', 'node compare.js' ]
11 silly lifecycle mse-live-player@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle mse-live-player@0.0.1~start: Failed to exec start script
13 verbose stack Error: mse-live-player@0.0.1 start: `node compare.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid mse-live-player@0.0.1
15 verbose cwd E:\Sources\Testing\mseLivePlayer
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.9.3
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error mse-live-player@0.0.1 start: `node compare.js`
22 error Exit status 1
23 error Failed at the mse-live-player@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by kevinGodell** [comment]
I made some changes to Mp4Frag to account for that situation. You can run `npm install mp4frag@latest` to get the fixed version(hopefully).  I was unable to duplicate the error on my windows, mac, or linux machines, but I am sure there must have been something that I missed.  Please let me know if it works.

**Comment by MinChanSike** [comment]
Thank you very much.
It is work for me. Service is not stopping now. 
Currently, some player instance are ```sometime stop playing``` and never start playing again.
I think it is cause by when I does not get enough bandwidth in browser.
After I refresh the page, stream are already playing again. 
I was tested in Chrome browser, 12 player instances and 2 source streams (800x450 & 1280x720). 
Thanks.

_Browser log_
```
2. player.min.js:1 VideoPlayer Error: video error error Namespace: testStream
_callback @ player.min.js:1
_onVideoError @ player.min.js:1
48. player.min.js:1 Uncaught DOMException: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.
    at a._onSegment (http://localhost:3000/public/player.min.js:1:12397)
    at r.emit (http://localhost:3000/socket.io/socket.io.js:1:12375)
    at r.onevent (http://localhost:3000/socket.io/socket.io.js:2:26293)
    at r.onpacket (http://localhost:3000/socket.io/socket.io.js:2:25957)
    at r.<anonymous> (http://localhost:3000/socket.io/socket.io.js:2:28033)
    at r.emit (http://localhost:3000/socket.io/socket.io.js:1:12375)
    at r.ondecoded (http://localhost:3000/socket.io/socket.io.js:1:18962)
    at s.<anonymous> (http://localhost:3000/socket.io/socket.io.js:2:28033)
    at s.r.emit (http://localhost:3000/socket.io/socket.io.js:1:12375)
    at s.add (http://localhost:3000/socket.io/socket.io.js:1:10956)
```

**Comment by kevinGodell** [comment]
My files are certainly not robust as it was meant to be an example to expand upon. One thing that would need to be done would be to monitor ffmpeg for exiting and automatically restart it and have the server send a new message to the browser. Also, the client side player does not monitor bandwidth usage so that it can adapt to changing network conditions. Personally, I use it to play and watch 14 different rtsp cams with all equipment on a local network and it simply works for me without failing 24/7. Someday, I may wrap all of the components into a robust solution that can take all situation into consideration.

**Comment by MinChanSike** [comment]
Anyhow, I never see before like your **MSE Live** rtsp player for _Web_.
Thank you.

**Comment by kevinGodell** [comment]
I added a little ffmpeg respawner code that should keep your ffmpeg process running if it is connected to an intermittent remote rtsp ip cam. It detects if connection stalls, then it will kill the process and re spawn it. It is in the compare.js example. Code still needs to be added so that the camera feed in the browser is told when the feed goes down and restarts on the server.
